version: '3'
services:
    springboot-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - angular-app

    angular-app:
        image: nginx:latest
        volumes:
            - ./paperless-ngx-ui:/usr/share/nginx/html
        ports:
            - "80:80"
